Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -45,7 +45,14 @@ jobs:
           # Replace $(AssemblyVersion) in version with the value of assemblyVersion
           version=$(echo "$version" | sed "s/\$(AssemblyVersion)/$assemblyVersion/g")
 
+          # Ensure version is valid
+          if [[ ! "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+(\.[0-9]+)?)?$ ]]; then
+            echo "::error::Invalid version format in Directory.Build.props: $VERSION"
+            exit 1
+          fi
+
           echo "Version=$version" >> $GITHUB_ENV
+          echo "Extracted and Resolved AssemblyVersion: $assemblyVersion"
           echo "Extracted and Resolved Version: $version"
 
       # 📝 Parse changelog for the version
@@ -56,6 +63,7 @@ jobs:
           changelog=$(awk "/^# $version /,/^# /{if (!/^# $version /) print}" CHANGELOG.md | sed '$d')
           echo "Changelog=$changelog" >> $GITHUB_ENV
           echo "Parsed changelog for version $version"
+          echo "$changelog"
 
       # 📦 Pack the project
       - name: 📦 Pack
